server:
  port: 9010
spring:
  redis:
    database: 0
    host: 192.168.3.14
    port: 6379
    password:
    timeout:
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait:
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.34:3306/oa?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: sa
    password: admin
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      pool-name: DatebookHikariCP
      connection-test-query: select 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    register: true
    nacos:
      discovery:
        server-addr: localhost:8848
file:
  upload-folder: "F:/officeOA/upload"

# Configure the Authorization Server and User Info Resource Server details
#security:
#  oauth2:
#    client:
#      accessTokenUri: http://localhost:7070/authserver/oauth/token
#      userAuthorizationUri: http://localhost:7070/authserver/oauth/authorize
#      clientId: first
#      clientSecret: passwordforauthserver
#    resource:
#      userInfoUri: http://localhost:9000/user
#person:
#  url: http://localhost:9000/person

#proxy:
#  auth:
#    routes:
#      api: oauth2