spring:
  application:
    name: waterProtect
  jackson:
    time-zone: GMT+8
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  mvc:
    date-format: "yyyy-MM-dd HH:mm:ss"
  profiles:
    active: dev
server:
  port: 8888
  servlet:
    context-path: /test
debug: true